### PR TITLE
Lib fix

### PR DESCRIPTION
**Pull request by lufton**
* Updated to work with new Google Auth routine.
* 2FA works from the box. No need to use CookieGetter or cli to obtain working cookie.
* Methods are still very unstable and dependent on Google Auth request system.

### CODE REVIEW

**Comment by royduin** [comment]
Please merge @costastf and tag a new version.

**Comment by zavorra** [comment]
please merge this patch

**Comment by GreatAnubis** [comment]
That patch works as expected! Thank you @lufton

**Comment by michaelarnauts** [comment]
Works perfect! Used this to generate a new cookie file, and that file is working fine with the current version packaged in HASS.

@costastf what's holding back from getting this merged in?

**Comment by costastf** [comment]
The reason is that the solution is very hardcoded and I consider it very fragile. On the other hand of course the current state is broken for most people so that does not say much :) . My plan is to completely decouple the library from the cookie getting process, so that the library requires the cookies as an argument. I am working on a tool that would use a browser for the user to go through the normal authentication process and retrieving the cookies using selenium. That still requires some work so in the mean time I will merge this and make a new version during the weekend.

**Comment by royduin** [comment]
Are you also tagging a new release for the time being?

**Comment by costastf** [comment]
I have released v3.0.11 with this patch already.

**Comment by royduin** [comment]
Don't see it here: https://github.com/costastf/locationsharinglib/releases or here: https://github.com/costastf/locationsharinglib/tags

**Comment by costastf** [comment]
I am not using github for releasing. You can find the released artifact in pypi https://pypi.org/project/locationsharinglib/

**Pull request merged**
