### PR TITLE
Automatically save and load cookies.

### LINKED ISSUE #4: Exporting of cookies should allow specifying the filename instead of the path
When exporting the cookies, the filename should be passed as a parameter instead of the path. This allows applications that use this library to have more flexibility on what filename to use.

The code to read the cookie file is already accepting filenames, so it makes sense to also be able to export to a custom file.

### PR DESCRIPTION
**Pull request by michaelarnauts**
This change makes the handling of cookies transparent for the application. If you specify a cookies_file, it will be loaded and saved to automatically. You can still leave it out and use authentication with email and password.

This cleans up the code I wrote for hass.

Fixes #4

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Note I'm not fluent in python, so my syntax can be a bit non-python. Feel free to suggest changes.

**Comment by costastf** [comment]
You have an non existent exception there so I will clean it up a bit and bump the version when done. I will let you know.

**Comment by michaelarnauts** [comment]
Great, thanks. I can then change the code for hass to just use `self.service = Service(self.username, self.password, CREDENTIALS_FILE)` and forget about the exporting and checking if the file exists.

Do you know by any change if the json also specifies the accuracy of the location? I saw a few integers that could indicate that, but I haven't looked into it deeper.

**Comment by costastf** [comment]
No, i do not really know. i think that on the previous component they use a value right after the lat-long as the accuracy and I could expose that the same way but not sure if it actually is that.

**Comment by costastf** [comment]
version 0.3.0 adds an accuracy attribute .

**Pull request merged**
